baseURL: "http://terranix.org"
languageCode: "en-us"
title: "terranix.org"
pygmentsUseClasses: true
sectionPagesMenu: "main"

markup:
  tableOfContents:
    endLevel: 6
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: solarized-light
    tabWidth: 2

menu:
  main:
    - name: "main"
      url: "/"
      weight: 1
      identifier: "main"

    - name: "news"
      url: "/news"
      weight: 2
      identifier: "news"

    - name: "documentation"
      url: "/documentation/"
      identifier: "documentation"
      weight: 3
      title: RTF(riendly)M

    - name: "options"
      url: "/options"
      identifier: "options"
      weight: 4
      title: opinionated terranix modules

