name: treefmt
on: [push, pull_request]
jobs:
  formatter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v23
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: treefmt
      run: nix-shell --run "treefmt --fail-on-change --no-cache"
